#!/usr/bin/env bash

installed_workflows=()
i=0

#
# Check for system arguments
#

# Describe command
if [[ ${1} == "description" ]]; then
  echo "  List currently installed workflows"
  exit 0
fi

#
# Read Alfred's plist
#

# Get possible "syncfolder"
retval=$(/usr/libexec/PlistBuddy -c "Print syncfolder" ${HOME}/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist 2> /dev/null)

# If error code => no syncfolder set => use "Application Support"
# Otherwise use the custom folder, returned by PlistBuddy
if [[ $? == 0 ]]; then
  workflow_folder="${retval}/Alfred.alfredpreferences/workflows"
else
  workflow_folder="${HOME}/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows"
fi

# Replace tilde with actual home folder
workflow_folder=${workflow_folder/#"~"/$HOME}

# Iterate through workflows
for workflow in "$workflow_folder"/*; do
  # Store relevant informations
  workflow_bundleid=$(/usr/libexec/PlistBuddy -c "Print bundleid" "${workflow}/Info.plist" 2> /dev/null)
  workflow_name=$(/usr/libexec/PlistBuddy -c "Print name" "${workflow}/Info.plist" 2> /dev/null)
  # Push to array
  installed_workflows[$i]=${workflow_name}
  ((i++))
done

# Show in colums
echo " ${installed_workflows[@]/%/$'\n'}" | sed 's/^ //' | column
