#!/usr/bin/env php
<?php
/*
 * Include functions
 */

$scriptdir=realpath(dirname(__FILE__));
include($scriptdir.'/../lib/functions.php');

/*
 * Check for system arguments
 */

// Describe command
if (isset($argv[1]) && $argv[1] == "description") {
  echo " Update the Workflow cache directly from packal.org";
  exit;
}

if(!isset($argv[1])) {
  std("error","No argument given");
  exit;
}

// TODO - search in cache

echo "$cache_file";

?>
